python3: can't open file '/source/./source/main.py': [Errno 2] No such file or directory
